SUM		START		4000
FIRST		LDX		ZERO		INITIALIZE REGISTERS
			LDA		ZERO
LOOP		ADD		TABLE,X		ADD THE ELEMENTS
			TIX		COUNT		ARE WE DONE?
			JLT		LOOP		IF NOT, LOOP
			STA		TOTAL		STORE THE TOTAL
			RSUB				AND RETURN
TABLE		RESW		2000		FOR THE ARRAY
COUNT		RESW		1		NUMBER OF ELEMENTS
ZERO		WORD		0		CONSTANT
TOTAL		RESW		1		PLACE FOR TOTAL
			END		FIRST